package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"iter"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/a2aproject/a2a-go/v2/a2a"
	"github.com/a2aproject/a2a-go/v2/a2asrv"
)

// agentEndpoint defines a team member agent
type agentEndpoint struct {
	Name        string
	Description string
	URL         string // A2A endpoint URL
	CardURL     string // Well-known agent card URL
}

type teamExecutor struct {
	agents []agentEndpoint
}

func (e *teamExecutor) Execute(ctx context.Context, execCtx *a2asrv.ExecutorContext) iter.Seq2[a2a.Event, error] {
	return func(yield func(a2a.Event, error) bool) {
		if execCtx.StoredTask == nil {
			if !yield(a2a.NewSubmittedTask(execCtx, execCtx.Message), nil) {
				return
			}
		}
		if !yield(a2a.NewStatusUpdateEvent(execCtx, a2a.TaskStateWorking, nil), nil) {
			return
		}

		text := extractText(execCtx.Message)
		log.Printf("[Team] Received: %s", text)

		report := e.runTeamAssessment(ctx, text)

		event := a2a.NewArtifactEvent(execCtx, a2a.NewTextPart(report))
		if !yield(event, nil) {
			return
		}
		yield(a2a.NewStatusUpdateEvent(execCtx, a2a.TaskStateCompleted, nil), nil)
	}
}

func (e *teamExecutor) Cancel(_ context.Context, execCtx *a2asrv.ExecutorContext) iter.Seq2[a2a.Event, error] {
	return func(yield func(a2a.Event, error) bool) {
		yield(a2a.NewStatusUpdateEvent(execCtx, a2a.TaskStateCanceled, nil), nil)
	}
}

func (e *teamExecutor) runTeamAssessment(ctx context.Context, text string) string {
	// Determine what to ask each agent based on the request
	tasks := e.planTasks(text)

	var results []string
	for _, task := range tasks {
		log.Printf("[Team] Delegating to %s: %s", task.agent.Name, task.prompt)

		// Discover agent card
		card, err := fetchCard(task.agent.CardURL)
		if err != nil {
			results = append(results, fmt.Sprintf("### %s\n**Error:** Could not reach agent: %v", task.agent.Name, err))
			continue
		}
		log.Printf("[Team] Agent %s has %d skills", card.Name, len(card.Skills))

		// Send A2A task
		response, err := sendA2AMessage(ctx, task.agent.URL, task.prompt)
		if err != nil {
			results = append(results, fmt.Sprintf("### %s\n**Error:** %v", task.agent.Name, err))
			continue
		}
		results = append(results, fmt.Sprintf("### %s\n%s", task.agent.Name, response))
	}

	timestamp := time.Now().Format("2006-01-02 15:04:05 MST")
	return fmt.Sprintf("# A2A Team Report\n**Timestamp:** %s\n**Agents consulted:** %d\n**Request:** %s\n\n---\n\n%s\n\n---\n*Report generated by A2A Team Coordinator*",
		timestamp, len(tasks), text, strings.Join(results, "\n\n"))
}

type agentTask struct {
	agent  agentEndpoint
	prompt string
}

func (e *teamExecutor) planTasks(text string) []agentTask {
	var tasks []agentTask

	for _, agent := range e.agents {
		switch {
		case strings.Contains(agent.Name, "Health"):
			if containsAny(text, "health", "status", "check", "overview", "node", "pod", "event") {
				tasks = append(tasks, agentTask{agent: agent, prompt: "Show cluster health summary"})
			}
		case strings.Contains(agent.Name, "Helm"):
			if containsAny(text, "health", "helm", "release", "deploy", "overview", "check") {
				tasks = append(tasks, agentTask{agent: agent, prompt: "List all helm releases across all namespaces"})
			}
		case strings.Contains(agent.Name, "K8s"):
			if containsAny(text, "health", "k8s", "kubernetes", "troubleshoot", "overview", "check") {
				tasks = append(tasks, agentTask{agent: agent, prompt: "Get cluster configuration and check for any issues"})
			}
		}
	}

	// Default: ask all agents if no specific match
	if len(tasks) == 0 {
		for _, agent := range e.agents {
			tasks = append(tasks, agentTask{agent: agent, prompt: text})
		}
	}
	return tasks
}

// sendA2AMessage sends a message to an A2A agent and extracts the text response.
// Supports both official A2A SDK format and kagent's format.
func sendA2AMessage(ctx context.Context, agentURL string, text string) (string, error) {
	// Detect method name based on URL
	// kagent uses "message/send", official SDK uses "SendMessage"
	method := "message/send"
	msgFormat := map[string]any{
		"role": "user",
		"parts": []map[string]any{
			{"kind": "text", "text": text},
		},
	}
	if !strings.Contains(agentURL, "/api/a2a/") {
		// Official a2a-go SDK format
		method = "SendMessage"
		msgFormat = map[string]any{
			"messageId": fmt.Sprintf("team-%d", time.Now().UnixNano()),
			"role":      "user",
			"parts":     []map[string]any{{"text": text}},
		}
	}

	payload := map[string]any{
		"jsonrpc": "2.0",
		"method":  method,
		"params": map[string]any{
			"message": msgFormat,
		},
		"id": 1,
	}

	body, _ := json.Marshal(payload)
	req, err := http.NewRequestWithContext(ctx, "POST", agentURL, bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	respBody, _ := io.ReadAll(resp.Body)

	// Parse JSON-RPC response — handle both kagent and official SDK formats
	var rpcResp struct {
		Result json.RawMessage `json:"result"`
		Error  *struct {
			Message string `json:"message"`
		} `json:"error"`
	}
	if err := json.Unmarshal(respBody, &rpcResp); err != nil {
		return "", fmt.Errorf("invalid response: %w", err)
	}
	if rpcResp.Error != nil {
		return "", fmt.Errorf("agent error: %s", rpcResp.Error.Message)
	}

	// Try to extract text from artifacts (both formats)
	var result struct {
		// Official SDK format
		Task struct {
			Artifacts []artifact `json:"artifacts"`
		} `json:"task"`
		// kagent format (artifacts at top level)
		Artifacts []artifact `json:"artifacts"`
	}
	json.Unmarshal(rpcResp.Result, &result)

	// Check kagent format first (more common)
	for _, a := range result.Artifacts {
		for _, p := range a.Parts {
			if p.Text != "" {
				return p.Text, nil
			}
		}
	}
	// Check official SDK format
	for _, a := range result.Task.Artifacts {
		for _, p := range a.Parts {
			if p.Text != "" {
				return p.Text, nil
			}
		}
	}

	return "(no text response)", nil
}

type artifact struct {
	Parts []struct {
		Text string `json:"text"`
	} `json:"parts"`
}

func fetchCard(cardURL string) (*a2a.AgentCard, error) {
	resp, err := http.Get(cardURL)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("status %d", resp.StatusCode)
	}
	var card a2a.AgentCard
	json.NewDecoder(resp.Body).Decode(&card)
	return &card, nil
}

func extractText(msg *a2a.Message) string {
	if msg == nil {
		return ""
	}
	for _, part := range msg.Parts {
		if t := part.Text(); t != "" {
			return strings.ToLower(t)
		}
	}
	return ""
}

func containsAny(text string, words ...string) bool {
	for _, w := range words {
		if strings.Contains(text, w) {
			return true
		}
	}
	return false
}

func main() {
	port := ":9092"
	if p := os.Getenv("PORT"); p != "" {
		port = ":" + p
	}

	// Custom standalone agent
	healthAgentURL := envOrDefault("HEALTH_AGENT_URL", "http://localhost:9090")
	// kagent agents (via kagent controller A2A endpoint)
	kagentBaseURL := envOrDefault("KAGENT_A2A_URL", "http://localhost:8083/api/a2a/kagent")

	agents := []agentEndpoint{
		{
			Name:        "K8s Health Agent (custom)",
			Description: "Custom A2A agent for cluster health checks",
			URL:         healthAgentURL + "/",
			CardURL:     healthAgentURL + "/.well-known/agent-card.json",
		},
		{
			Name:        "Helm Agent (kagent)",
			Description: "kagent built-in Helm release management agent",
			URL:         kagentBaseURL + "/helm-agent/",
			CardURL:     kagentBaseURL + "/helm-agent/.well-known/agent.json",
		},
		{
			Name:        "K8s Agent (kagent)",
			Description: "kagent built-in Kubernetes operations agent",
			URL:         kagentBaseURL + "/k8s-agent/",
			CardURL:     kagentBaseURL + "/k8s-agent/.well-known/agent.json",
		},
	}

	executor := &teamExecutor{agents: agents}
	handler := a2asrv.NewHandler(executor)
	jsonrpcHandler := a2asrv.NewJSONRPCHandler(handler)

	card := &a2a.AgentCard{
		Name:        "A2A Team Coordinator",
		Description: "Orchestrates a team of AI agents (custom + kagent) via A2A protocol for comprehensive cluster assessment.",
		Version:     "0.1.0",
		Provider: &a2a.AgentProvider{
			Org: "AI Reliability Engineering",
			URL: "https://github.com/kyrylyuk-andriy/ai-reliability-engineering",
		},
		DefaultInputModes:  []string{"text/plain"},
		DefaultOutputModes: []string{"text/plain"},
		Skills: []a2a.AgentSkill{
			{ID: "team-assessment", Name: "Team Assessment", Description: "Full cluster assessment using all team agents"},
			{ID: "team-health", Name: "Team Health Check", Description: "Health check delegated across the agent team"},
		},
		SupportedInterfaces: []*a2a.AgentInterface{
			a2a.NewAgentInterface(fmt.Sprintf("http://localhost%s", port), a2a.TransportProtocolJSONRPC),
		},
	}

	mux := http.NewServeMux()
	mux.Handle(a2asrv.WellKnownAgentCardPath, a2asrv.NewStaticAgentCardHandler(card))
	mux.Handle("/", jsonrpcHandler)

	log.Printf("A2A Team Coordinator started on %s", port)
	log.Printf("Agent Card: http://localhost%s%s", port, a2asrv.WellKnownAgentCardPath)
	log.Printf("Team members:")
	for _, a := range agents {
		log.Printf("  - %s → %s", a.Name, a.URL)
	}
	if err := http.ListenAndServe(port, mux); err != nil {
		log.Fatalf("Server failed: %v", err)
	}
}

func envOrDefault(key, def string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return def
}
