package main

import (
	"context"
	"encoding/json"
	"fmt"
	"iter"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/a2aproject/a2a-go/v2/a2a"
	"github.com/a2aproject/a2a-go/v2/a2aclient"
	"github.com/a2aproject/a2a-go/v2/a2asrv"
)

type sreExecutor struct {
	healthAgentURL string
}

func (e *sreExecutor) Execute(ctx context.Context, execCtx *a2asrv.ExecutorContext) iter.Seq2[a2a.Event, error] {
	return func(yield func(a2a.Event, error) bool) {
		if execCtx.StoredTask == nil {
			if !yield(a2a.NewSubmittedTask(execCtx, execCtx.Message), nil) {
				return
			}
		}
		if !yield(a2a.NewStatusUpdateEvent(execCtx, a2a.TaskStateWorking, nil), nil) {
			return
		}

		text := extractText(execCtx.Message)
		log.Printf("[SRE Coordinator] Received task: %s", text)

		report := e.runChecks(ctx, text)

		event := a2a.NewArtifactEvent(execCtx, a2a.NewTextPart(report))
		if !yield(event, nil) {
			return
		}
		yield(a2a.NewStatusUpdateEvent(execCtx, a2a.TaskStateCompleted, nil), nil)
	}
}

func (e *sreExecutor) Cancel(_ context.Context, execCtx *a2asrv.ExecutorContext) iter.Seq2[a2a.Event, error] {
	return func(yield func(a2a.Event, error) bool) {
		yield(a2a.NewStatusUpdateEvent(execCtx, a2a.TaskStateCanceled, nil), nil)
	}
}

func (e *sreExecutor) runChecks(ctx context.Context, text string) string {
	var checks []string

	switch {
	case containsAny(text, "health", "status", "check", "overview", "summary"):
		checks = []string{
			"Show me the cluster node status",
			"Show pods in kagent namespace",
			"Show any warning events",
		}
	case containsAny(text, "incident", "alert", "problem", "issue"):
		checks = []string{
			"Show any warning events",
			"Show me the cluster node status",
			"Show pods in kube-system namespace",
		}
	default:
		checks = []string{
			"Show me the cluster node status",
			"Show pods in kagent namespace",
		}
	}

	// Discover the agent card
	agentCard, err := fetchAgentCard(e.healthAgentURL)
	if err != nil {
		return fmt.Sprintf("Error: Failed to discover Health Agent: %v", err)
	}
	log.Printf("[SRE Coordinator] Connected to agent: %s (v%s) with %d skills",
		agentCard.Name, agentCard.Version, len(agentCard.Skills))

	// Create A2A client from the agent card
	a2aClient, err := a2aclient.NewFromCard(ctx, agentCard)
	if err != nil {
		return fmt.Sprintf("Error: Failed to create A2A client: %v", err)
	}

	var results []string
	for i, check := range checks {
		log.Printf("[SRE Coordinator] Sending check %d/%d: %s", i+1, len(checks), check)

		msg := a2a.NewMessage(a2a.MessageRoleUser, a2a.NewTextPart(check))
		resp, err := a2aClient.SendMessage(ctx, &a2a.SendMessageRequest{
			Message: msg,
		})
		if err != nil {
			results = append(results, fmt.Sprintf("## Check %d: FAILED\n%v", i+1, err))
			continue
		}

		// Extract text from the response
		resultText := extractResultText(resp)
		if resultText != "" {
			results = append(results, fmt.Sprintf("## Check %d: %s\n%s", i+1, check, resultText))
		} else {
			results = append(results, fmt.Sprintf("## Check %d: %s\n(no text response)", i+1, check))
		}
	}

	timestamp := time.Now().Format("2006-01-02 15:04:05 MST")
	return fmt.Sprintf("# SRE Health Report\nTimestamp: %s\nHealth Agent: %s (v%s)\nChecks performed: %d\n\n%s\n\n---\nReport generated by SRE Coordinator Agent",
		timestamp, agentCard.Name, agentCard.Version, len(checks), strings.Join(results, "\n\n"))
}

func fetchAgentCard(baseURL string) (*a2a.AgentCard, error) {
	cardURL := strings.TrimSuffix(baseURL, "/") + "/.well-known/agent-card.json"
	resp, err := http.Get(cardURL)
	if err != nil {
		return nil, fmt.Errorf("HTTP GET failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status: %d", resp.StatusCode)
	}
	var card a2a.AgentCard
	if err := json.NewDecoder(resp.Body).Decode(&card); err != nil {
		return nil, fmt.Errorf("decode failed: %w", err)
	}
	return &card, nil
}

func extractResultText(resp a2a.SendMessageResult) string {
	raw, _ := json.Marshal(resp)
	var parsed struct {
		Artifacts []struct {
			Parts []struct {
				Text string `json:"text"`
			} `json:"parts"`
		} `json:"artifacts"`
		Parts []struct {
			Text string `json:"text"`
		} `json:"parts"`
	}
	json.Unmarshal(raw, &parsed)

	// Check artifacts (Task response)
	for _, a := range parsed.Artifacts {
		for _, p := range a.Parts {
			if p.Text != "" {
				return p.Text
			}
		}
	}
	// Check message parts
	for _, p := range parsed.Parts {
		if p.Text != "" {
			return p.Text
		}
	}
	return ""
}

func extractText(msg *a2a.Message) string {
	if msg == nil {
		return ""
	}
	for _, part := range msg.Parts {
		if t := part.Text(); t != "" {
			return strings.ToLower(t)
		}
	}
	return ""
}

func containsAny(text string, words ...string) bool {
	for _, w := range words {
		if strings.Contains(text, w) {
			return true
		}
	}
	return false
}

func main() {
	port := ":9091"
	if p := os.Getenv("PORT"); p != "" {
		port = ":" + p
	}

	healthAgentURL := "http://localhost:9090/"
	if u := os.Getenv("HEALTH_AGENT_URL"); u != "" {
		healthAgentURL = u
	}

	executor := &sreExecutor{healthAgentURL: healthAgentURL}
	handler := a2asrv.NewHandler(executor)
	jsonrpcHandler := a2asrv.NewJSONRPCHandler(handler)

	card := &a2a.AgentCard{
		Name:        "SRE Coordinator Agent",
		Description: "Orchestrates SRE tasks by delegating to specialized agents via A2A protocol.",
		Version:     "0.1.0",
		Provider: &a2a.AgentProvider{
			Org: "AI Reliability Engineering",
			URL: "https://github.com/kyrylyuk-andriy/ai-reliability-engineering",
		},
		DefaultInputModes:  []string{"text/plain"},
		DefaultOutputModes: []string{"text/plain"},
		Skills: []a2a.AgentSkill{
			{ID: "health-assessment", Name: "Cluster Health Assessment", Description: "Comprehensive health check via K8s Health Agent"},
			{ID: "incident-triage", Name: "Incident Triage", Description: "Initial incident triage — checks events, nodes, and system pods"},
		},
		SupportedInterfaces: []*a2a.AgentInterface{
			a2a.NewAgentInterface(fmt.Sprintf("http://localhost%s", port), a2a.TransportProtocolJSONRPC),
		},
	}

	mux := http.NewServeMux()
	mux.Handle(a2asrv.WellKnownAgentCardPath, a2asrv.NewStaticAgentCardHandler(card))
	mux.Handle("/", jsonrpcHandler)

	log.Printf("SRE Coordinator Agent started on %s (official a2a-go SDK)", port)
	log.Printf("Agent Card: http://localhost%s%s", port, a2asrv.WellKnownAgentCardPath)
	log.Printf("Delegating to Health Agent at: %s", healthAgentURL)
	if err := http.ListenAndServe(port, mux); err != nil {
		log.Fatalf("Server failed: %v", err)
	}
}
