package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"strings"
	"time"

	"trpc.group/trpc-go/trpc-a2a-go/client"
	"trpc.group/trpc-go/trpc-a2a-go/protocol"
	"trpc.group/trpc-go/trpc-a2a-go/server"
	"trpc.group/trpc-go/trpc-a2a-go/taskmanager"
)

// sreProcessor is the SRE Coordinator that delegates to downstream agents via A2A.
type sreProcessor struct {
	healthAgentURL string
}

func (p *sreProcessor) ProcessMessage(
	ctx context.Context,
	message protocol.Message,
	options taskmanager.ProcessOptions,
	handle taskmanager.TaskHandler,
) (*taskmanager.MessageProcessingResult, error) {
	text := extractText(message)
	log.Printf("[SRE Coordinator] Received task: %s", text)

	var results []string
	var checks []string

	switch {
	case containsAny(text, "health", "status", "check", "overview", "summary"):
		checks = []string{
			"Show me the cluster node status",
			"Show pods in kagent namespace",
			"Show any warning events",
		}
	case containsAny(text, "incident", "alert", "problem", "issue"):
		checks = []string{
			"Show any warning events",
			"Show me the cluster node status",
			"Show pods in kube-system namespace",
		}
	case containsAny(text, "pod", "pods"):
		checks = []string{text}
	case containsAny(text, "node", "nodes"):
		checks = []string{text}
	case containsAny(text, "deploy", "deployment"):
		checks = []string{text}
	default:
		checks = []string{
			"Show me the cluster node status",
			"Show pods in kagent namespace",
		}
	}

	// Create A2A client to communicate with the health agent
	a2aClient, err := client.NewA2AClient(p.healthAgentURL)
	if err != nil {
		return errorResult(fmt.Sprintf("Failed to create A2A client: %v", err)), nil
	}

	// Discover the agent card via HTTP GET
	agentCard, err := fetchAgentCard(p.healthAgentURL)
	if err != nil {
		return errorResult(fmt.Sprintf("Failed to discover Health Agent: %v", err)), nil
	}
	log.Printf("[SRE Coordinator] Connected to agent: %s (v%s) with %d skills",
		agentCard.Name, agentCard.Version, len(agentCard.Skills))

	// Send each check as an A2A task
	for i, check := range checks {
		log.Printf("[SRE Coordinator] Sending check %d/%d: %s", i+1, len(checks), check)

		msg := protocol.NewMessage(
			protocol.MessageRoleUser,
			[]protocol.Part{protocol.NewTextPart(check)},
		)
		params := protocol.SendMessageParams{
			Message: msg,
		}

		result, err := a2aClient.SendMessage(ctx, params)
		if err != nil {
			results = append(results, fmt.Sprintf("## Check %d: FAILED\n%v", i+1, err))
			continue
		}

		// Extract text from the result
		if result.Result != nil {
			// Marshal/unmarshal to extract text from the result
			raw, _ := json.Marshal(result.Result)
			var parsed struct {
				Parts []struct {
					Kind string `json:"kind"`
					Text string `json:"text"`
				} `json:"parts"`
			}
			json.Unmarshal(raw, &parsed)
			for _, part := range parsed.Parts {
				if part.Kind == "text" && part.Text != "" {
					results = append(results, fmt.Sprintf("## Check %d: %s\n%s", i+1, check, part.Text))
				}
			}
		}
	}

	// Compile the SRE report
	timestamp := time.Now().Format("2006-01-02 15:04:05 MST")
	report := fmt.Sprintf("# SRE Health Report\nTimestamp: %s\nHealth Agent: %s (v%s)\nChecks performed: %d\n\n%s\n\n---\nReport generated by SRE Coordinator Agent",
		timestamp, agentCard.Name, agentCard.Version, len(checks), strings.Join(results, "\n\n"))

	responseMessage := protocol.NewMessage(
		protocol.MessageRoleAgent,
		[]protocol.Part{protocol.NewTextPart(report)},
	)
	return &taskmanager.MessageProcessingResult{
		Result: &responseMessage,
	}, nil
}

func fetchAgentCard(baseURL string) (*server.AgentCard, error) {
	cardURL := strings.TrimSuffix(baseURL, "/") + "/.well-known/agent.json"
	resp, err := http.Get(cardURL)
	if err != nil {
		return nil, fmt.Errorf("HTTP GET failed: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status: %d", resp.StatusCode)
	}
	var card server.AgentCard
	if err := json.NewDecoder(resp.Body).Decode(&card); err != nil {
		return nil, fmt.Errorf("decode failed: %w", err)
	}
	return &card, nil
}

func errorResult(msg string) *taskmanager.MessageProcessingResult {
	m := protocol.NewMessage(
		protocol.MessageRoleAgent,
		[]protocol.Part{protocol.NewTextPart("Error: " + msg)},
	)
	return &taskmanager.MessageProcessingResult{Result: &m}
}

func extractText(msg protocol.Message) string {
	for _, part := range msg.Parts {
		if tp, ok := part.(protocol.TextPart); ok {
			return strings.ToLower(tp.Text)
		}
	}
	return ""
}

func containsAny(text string, words ...string) bool {
	for _, w := range words {
		if strings.Contains(text, w) {
			return true
		}
	}
	return false
}

func stringPtr(s string) *string { return &s }
func boolPtr(b bool) *bool       { return &b }

func main() {
	port := ":9091"
	if p := os.Getenv("PORT"); p != "" {
		port = ":" + p
	}

	healthAgentURL := "http://localhost:9090/"
	if u := os.Getenv("HEALTH_AGENT_URL"); u != "" {
		healthAgentURL = u
	}

	processor := &sreProcessor{healthAgentURL: healthAgentURL}

	providerURL := "https://github.com/kyrylyuk-andriy/ai-reliability-engineering"

	agentCard := server.AgentCard{
		Name:        "SRE Coordinator Agent",
		Description: "Orchestrates SRE tasks by delegating to specialized agents via A2A protocol. Performs cluster health assessments, incident triage, and generates SRE reports.",
		URL:         fmt.Sprintf("http://localhost%s/", port),
		Version:     "0.1.0",
		Provider: &server.AgentProvider{
			Organization: "AI Reliability Engineering",
			URL:          &providerURL,
		},
		Capabilities: server.AgentCapabilities{
			Streaming:         boolPtr(false),
			PushNotifications: boolPtr(false),
		},
		DefaultInputModes:  []string{protocol.KindText},
		DefaultOutputModes: []string{protocol.KindText},
		Skills: []server.AgentSkill{
			{
				ID:          "health-assessment",
				Name:        "Cluster Health Assessment",
				Description: stringPtr("Comprehensive cluster health check by delegating to the K8s Health Agent"),
				InputModes:  []string{protocol.KindText},
				OutputModes: []string{protocol.KindText},
			},
			{
				ID:          "incident-triage",
				Name:        "Incident Triage",
				Description: stringPtr("Initial incident triage — checks events, nodes, and system pods"),
				InputModes:  []string{protocol.KindText},
				OutputModes: []string{protocol.KindText},
			},
		},
	}

	taskManager, err := taskmanager.NewMemoryTaskManager(processor)
	if err != nil {
		log.Fatalf("Failed to create task manager: %v", err)
	}

	srv, err := server.NewA2AServer(agentCard, taskManager)
	if err != nil {
		log.Fatalf("Failed to create A2A server: %v", err)
	}

	log.Printf("SRE Coordinator Agent started on %s", port)
	log.Printf("Agent Card: http://localhost%s/.well-known/agent.json", port)
	log.Printf("Delegating to Health Agent at: %s", healthAgentURL)
	if err := srv.Start(port); err != nil {
		log.Fatalf("Server failed: %v", err)
	}
}
