apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - agentgateway.yaml
  - kagent.yaml
  - kmcp-server.yaml
  - mcpg.yaml
  - agentregistry.yaml
  - phoenix.yaml
  - qdrant.yaml
  - prompt-enrichment.yaml
