apiVersion: v1
kind: Namespace
metadata:
  name: phoenix
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: phoenix
  namespace: phoenix
spec:
  interval: 1h
  url: oci://registry-1.docker.io/arizephoenix/phoenix-helm
  ref:
    tag: "5.0.20"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: phoenix
  namespace: phoenix
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: phoenix
  values:
    server:
      port: 6006
    auth:
      enableAuth: false
